export const SOBRE_MI = {
  titleSuperior: "Sobre mí",

  contentSuperior: `¡Hola! Iniciada en el mundo de la programación como junior, con muchas ganas de llevar a cabo todo lo aprendido en diferentes bootcamps, como en las plataformas interactivas: <a href="https://www.qualentum.com/candidato/frontend-developer/" target="_blank">Qualentum</a>, <a href="https://www.joyofreact.com/"target="_blank">Josh W Comeau's</a>, <a href="https://practical-accessibility.today/" target="_blank">Practical Accessibility con Sara Soueidan</a>, <a href="https://platzi.com" target="_blank">Platzi</a>, <a href="https://scrimba.com/learn/frontend" target="_blank">Scrimba</a> y <a href="https://www.freecodecamp.org/" target="_blank">FreeCodeCamp</a>. Con mucha disposición, determinación y voluntad para seguir aprendiendo. Espero a que os animéis a contactarme. Gracias de antemano.`,
  titleInferior: "Habilidades",
  contentInferior: [
    "Next.js",
    "React",
    "React Router",
    "Redux",
    "JavaScript",
    "ES6",
    "CSS & HTML",
    "Open Cells",
    "LitElement",
    "Web Components",
    "Testing: Jest, React Testing Library",
    "Figma",
    "Accesibilidad",
    "Git",
    "GitHub",
    "Firebase",
    "Netlify",
    "Vercel",
  ],
};
